version: '3.9'

services:
  gpt-service:
    build: .
    container_name: gpt-service
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION_ID: ${OPENAI_ORGANIZATION_ID}
      OPENAI_PROJECT_ID: ${OPENAI_PROJECT_ID}
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped
